FROM nginx:alpine

COPY index.html /usr/share/nginx/html/
COPY src /usr/share/nginx/html/src/

COPY docker-entrypoint.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh

EXPOSE 80

ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]